server:
  port: 8087
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show_sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms-clientegym
    username: root
    password:

<<<<<<< HEAD
  eureka:
    client:
      serviceUrl:
        defaultZone: http://localhost:8091/eureka
    instance:
      hostname: localhost
=======
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka
  instance:
    hostname: localhost
>>>>>>> b1b78c875b33ae320fe514cc8baeae074860f4a6
