server:
  port: 8087
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show_sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ms-clientegym
    username: root
    password:

<<<<<<< HEAD

=======
>>>>>>> b8890b18978f21687df35fb0013976af85dad3f2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka
  instance:
    hostname: localhost
<<<<<<< HEAD

=======
>>>>>>> b8890b18978f21687df35fb0013976af85dad3f2
