server:
  port: 8099


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka
  instance:
    hostname: localhost


spring:
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: ms-clientegym-service
          uri: lb://ms-clientegym-service
          predicates:
            - Path=/clientegym/**
        - id: ms-membresia-service
          uri: lb://ms-membresia-service
          predicates:
            - Path=/membresia/**
